version: "3.7"
services:
  db:
    platform: linux/x86_64 # <-- Add this line
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: t2htest
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: t2htest
      MYSQL_PASSWORD: t2htest
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 3306:3306
